INSERT INTO KHINKA."Buckets" (ID, ITEM, AMOUNT) VALUES (2, 4, 2);
INSERT INTO KHINKA."Buckets" (ID, ITEM, AMOUNT) VALUES (2, 1, 10);
INSERT INTO KHINKA."Buckets" (ID, ITEM, AMOUNT) VALUES (33, 2, 5);
INSERT INTO KHINKA."Buckets" (ID, ITEM, AMOUNT) VALUES (33, 1, 3);
INSERT INTO KHINKA."Buckets" (ID, ITEM, AMOUNT) VALUES (33, 34, 1);